"""Moving a training stage between GitHub Actions jobs.

A workflow job starts on a clean machine: nothing from the previous job's
filesystem exists. State crosses the gap only as a GitHub *artifact*, so this
module defines that artifact — the **stage bundle** — and the checks a job
runs on an incoming one *before it trusts it*:

    bundle/
      bundle_manifest.json     identity + SHA-256 of every file below
      checkpoints/             latest + previous training checkpoint (+ latest.json/previous.json)
      export/                  the inference package written at the end of the run
      training_summary.json    generated by the run
      metrics.jsonl, runner_profile.json, eval_results.json   (when present)

``bundle_manifest.json`` records ``run_id``, ``stage``, ``global_step``,
``model_config_hash``, ``tokenizer_hash``, ``dataset_hash``,
``training_config_hash`` and the SHA-256 of the checkpoint's own manifest. An
artifact *name* alone is never trusted to identify a checkpoint: the receiving
job re-derives every one of those from the files, requires them to agree with
the bundle manifest, requires the model config to equal the profile it is about
to train with, and (optionally) that the checkpoint manifest hash equals a value
the operator pinned in the workflow inputs.

Modes: ``fresh`` (no artifact), ``resume`` (same stage, not yet complete: exact
continuation via ``tinymind train --resume``), ``init-from`` (next stage: weights
from a *completed* stage via ``--init-from``, after the optional promotion gate).

CLI (used by ``.github/workflows/train-stage.yml``)::

    python -m tinymind.ci.stage_io runtime      --max-hours 5
    python -m tinymind.ci.stage_io check-incoming --dir incoming --stage stage2 --profile-config configs/tiny_mobile.yaml [--mode auto] [--expect-manifest-sha256 H] [--gate-dir configs/stages] [--skip-gate]
    python -m tinymind.ci.stage_io bundle       --run out --dest bundle --profile tiny_mobile --stage stage2 [--eval out/eval_results.json]
    python -m tinymind.ci.stage_io summary      --bundle bundle
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Any

from tinymind.model.config import ModelConfig
from tinymind.training import checkpoint as ck

BUNDLE_KIND = "tinymind-stage-bundle"
BUNDLE_FORMAT = 1
MAX_HOURS = 5.5          # GitHub-hosted jobs are killed at 6 h; leave room for setup and upload
RESERVE_SECONDS = 15 * 60  # setup + data generation + eval + upload happen outside the trainer's budget


class BundleError(Exception):
    pass


def _sha(path: Path) -> str:
    return ck.sha256_file(path)


def artifact_name(profile: str, stage: str, step: int, commit_or_run: str) -> str:
    """Deterministic and collision-free: ``tinymind-<profile>-<stage>-step<NNNNNN>-<git sha7 or run id>``."""
    return f"tinymind-{profile}-{stage}-step{step:06d}-{commit_or_run[:7]}"


def runtime_seconds(max_hours: float) -> int:
    """Wall-clock budget to hand ``tinymind train --max-runtime``: the operator's ``max_hours`` minus the time the
    job spends outside training. Rejects requests that would run into the platform's 6 h kill."""
    if not 0.05 <= max_hours <= MAX_HOURS:
        raise BundleError(f"max_hours must be between 0.05 and {MAX_HOURS} (hosted runners are killed at 6 h), got {max_hours}")
    return max(60, int(max_hours * 3600) - RESERVE_SECONDS)


# ---------------------------------------------------------------------------------------- bundling
def bundle_run(run_dir: str | Path, dest: str | Path, *, profile: str, stage: str, run_id: str | None = None,
               extra_files: dict[str, Path] | None = None) -> dict[str, Any]:
    run, dest = Path(run_dir), Path(dest)
    root = run / "checkpoints"
    latest, notes = ck.find_latest_valid(root)
    if latest is None:
        raise BundleError(f"no valid checkpoint under {root} to bundle ({'; '.join(notes)})")
    if dest.exists():
        shutil.rmtree(dest)
    (dest / "checkpoints").mkdir(parents=True)
    keep = {latest.name}
    for pointer in ("previous.json",):
        try:
            keep.add(json.loads((root / pointer).read_text())["checkpoint"])
        except (OSError, ValueError, KeyError):
            pass
    for name in sorted(keep):
        if ck.verify_checkpoint(root / name).ok:
            shutil.copytree(root / name, dest / "checkpoints" / name)
    # the pointers must name what was actually copied
    (dest / "checkpoints" / "latest.json").write_text(json.dumps({
        "checkpoint": latest.name, "manifest_sha256": _sha(latest / "manifest.json"), "global_step": int(latest.name.split("-")[1])}, indent=2))
    prev = [n for n in sorted(keep) if n != latest.name and (dest / "checkpoints" / n).exists()]
    if prev:
        (dest / "checkpoints" / "previous.json").write_text(json.dumps({
            "checkpoint": prev[-1], "manifest_sha256": _sha(root / prev[-1] / "manifest.json"), "global_step": int(prev[-1].split("-")[1])}, indent=2))
    if (run / "export").is_dir():
        shutil.copytree(run / "export", dest / "export")
    for name in ("training_summary.json", "metrics.jsonl"):
        if (run / name).is_file():
            shutil.copy2(run / name, dest / name)
    for name, src in (extra_files or {}).items():
        if Path(src).is_file():
            shutil.copy2(src, dest / name)

    manifest_c = json.loads((latest / "manifest.json").read_text())
    commit = manifest_c.get("git_commit") or os.environ.get("GITHUB_SHA") or "nogit"
    manifest = {
        "kind": BUNDLE_KIND, "format_version": BUNDLE_FORMAT, "profile": profile, "stage": manifest_c["stage"],
        "global_step": manifest_c["global_step"], "stage_complete": manifest_c["stage_complete"],
        "run_id": run_id or os.environ.get("GITHUB_RUN_ID"), "run_attempt": os.environ.get("GITHUB_RUN_ATTEMPT"),
        "git_commit": manifest_c.get("git_commit"), "checkpoint": latest.name,
        "checkpoint_manifest_sha256": _sha(latest / "manifest.json"),
        "model_config_hash": manifest_c["model_config_hash"], "tokenizer_hash": manifest_c["tokenizer_hash"],
        "dataset_hash": manifest_c["dataset_hash"], "training_config_hash": manifest_c["training_config_hash"],
        "model_parameter_count": manifest_c["model_parameter_count"],
        "artifact_name": artifact_name(profile, manifest_c["stage"], manifest_c["global_step"], commit if commit != "nogit" else str(run_id or "local")),
        "created_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
        "files": {},
    }
    if manifest_c["stage"] != stage:
        raise BundleError(f"the run's checkpoint is stage {manifest_c['stage']!r} but the workflow says {stage!r}")
    for f in sorted(p for p in dest.rglob("*") if p.is_file()):
        manifest["files"][str(f.relative_to(dest))] = {"sha256": _sha(f), "size": f.stat().st_size}
    (dest / "bundle_manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return manifest


# ---------------------------------------------------------------------------------------- verifying
def verify_bundle(directory: str | Path) -> tuple[dict[str, Any], Path]:
    """Return ``(bundle_manifest, verified latest checkpoint dir)`` or raise ``BundleError`` listing every problem."""
    d = Path(directory)
    problems: list[str] = []
    mpath = d / "bundle_manifest.json"
    if not mpath.is_file():
        raise BundleError(f"{d}: bundle_manifest.json missing (not a stage bundle?)")
    try:
        m = json.loads(mpath.read_text())
    except ValueError as exc:
        raise BundleError(f"{mpath}: unreadable ({exc})") from exc
    if m.get("kind") != BUNDLE_KIND or m.get("format_version") != BUNDLE_FORMAT:
        raise BundleError(f"unsupported bundle kind/version {m.get('kind')!r}/{m.get('format_version')!r}")
    for rel, info in m.get("files", {}).items():
        f = d / rel
        if not f.is_file():
            problems.append(f"{rel} missing")
        elif f.stat().st_size != info["size"] or _sha(f) != info["sha256"]:
            problems.append(f"{rel} does not match its recorded size/SHA-256 (corrupt or partial download)")
    if problems:
        raise BundleError("; ".join(problems))
    latest = d / "checkpoints" / m["checkpoint"]
    report = ck.verify_checkpoint(latest)
    if not report.ok:
        raise BundleError(f"checkpoint {m['checkpoint']} failed verification: " + "; ".join(report.errors))
    cm = report.manifest
    assert cm is not None
    if _sha(latest / "manifest.json") != m["checkpoint_manifest_sha256"]:
        problems.append("checkpoint manifest SHA-256 differs from the bundle manifest")
    for key in ("stage", "global_step", "stage_complete", "model_config_hash", "tokenizer_hash", "dataset_hash", "training_config_hash"):
        if cm[key] != m[key]:
            problems.append(f"{key}: bundle says {m[key]!r}, checkpoint says {cm[key]!r}")
    if problems:
        raise BundleError("; ".join(problems))
    return m, latest


def resolve_mode(m: dict[str, Any], *, stage: str, requested: str = "auto") -> str:
    same = m["stage"] == stage
    complete = bool(m["stage_complete"])
    if requested == "resume" or (requested == "auto" and same and not complete):
        if not same:
            raise BundleError(f"cannot resume: artifact is stage {m['stage']!r}, this run is {stage!r}")
        if complete:
            raise BundleError(f"cannot resume: {stage} is already complete in this artifact (step {m['global_step']}); "
                              "start the next stage from it, or re-run this stage from scratch")
        return "resume"
    if requested == "init-from" or (requested == "auto" and not same and complete):
        if not complete:
            raise BundleError(f"cannot start {stage} from {m['stage']!r}: that stage is not complete (step {m['global_step']}); "
                              "resume it first")
        if same:
            raise BundleError(f"refusing to initialise stage {stage} from its own completed checkpoint")
        return "init-from"
    if requested == "auto":
        raise BundleError(f"cannot decide: artifact is stage {m['stage']!r} (complete={complete}), this run is {stage!r}")
    raise BundleError(f"unknown mode {requested!r}")


def check_incoming(directory: str | Path, *, stage: str, profile_config: str | Path, requested_mode: str = "auto",
                   expect_manifest_sha256: str | None = None, gate_dir: str | Path | None = None,
                   skip_gate: bool = False) -> dict[str, Any]:
    """Everything a job verifies before it trusts an incoming artifact. Returns the decision
    ``{"mode", "checkpoint", "bundle": {...}, "gate": {...}|None}``; raises ``BundleError`` otherwise.
    Promotion (``init-from``) runs the parent stage's gate, ``<gate_dir>/<parent stage>.gate.json``, unless
    ``skip_gate``; a missing gate file is reported in the decision, not silently ignored."""
    m, latest = verify_bundle(directory)
    problems: list[str] = []
    want_hash = ModelConfig.from_yaml(profile_config).stable_hash()
    if m["model_config_hash"] != want_hash:
        problems.append(f"model architecture differs: the artifact was trained with config hash {m['model_config_hash'][:12]}…, "
                        f"{profile_config} hashes to {want_hash[:12]}…")
    if expect_manifest_sha256 and m["checkpoint_manifest_sha256"] != expect_manifest_sha256:
        problems.append("checkpoint manifest SHA-256 differs from the value pinned in the workflow inputs")
    if problems:
        raise BundleError("; ".join(problems))
    mode = resolve_mode(m, stage=stage, requested=requested_mode)
    verdict: dict[str, Any] | None = None
    if mode == "init-from" and gate_dir and not skip_gate:
        from tinymind.training.gate import evaluate_gate
        gate_file = Path(gate_dir) / f"{m['stage']}.gate.json"
        base = Path(directory)
        if gate_file.is_file():
            summary = json.loads((base / "training_summary.json").read_text()) if (base / "training_summary.json").is_file() else None
            evals = json.loads((base / "eval_results.json").read_text()) if (base / "eval_results.json").is_file() else None
            verdict = evaluate_gate(json.loads(gate_file.read_text()), summary=summary, eval_results=evals)
            if not verdict["passed"]:
                failed = [c for c in verdict["checks"] if not c["ok"]]
                raise BundleError("promotion gate FAILED: " + "; ".join(
                    f"{c['check']}={c['value']!r} (needs {c['requirement']})" for c in failed))
        else:
            verdict = {"passed": None, "note": f"no gate file {gate_file}; promotion was not gated"}
    return {"mode": mode, "checkpoint": str(Path(directory) / "checkpoints"), "bundle": m, "gate": verdict}


# ---------------------------------------------------------------------------------------- reporting
def summary_markdown(bundle: dict[str, Any], summary: dict[str, Any] | None, gate: dict[str, Any] | None = None,
                     eval_results: dict[str, Any] | None = None) -> str:
    lines = [f"## {bundle['profile']} — {bundle['stage']}", "",
             f"| | |", "|---|---|",
             f"| step | {bundle['global_step']} ({'**stage complete**' if bundle['stage_complete'] else 'stage NOT complete — resume it'}) |",
             f"| parameters | {bundle['model_parameter_count']:,} |",
             f"| artifact | `{bundle['artifact_name']}` |",
             f"| checkpoint manifest sha256 | `{bundle['checkpoint_manifest_sha256']}` |",
             f"| model / dataset / config hash | `{bundle['model_config_hash'][:12]}` / `{bundle['dataset_hash'][:12]}` / `{bundle['training_config_hash'][:12]}` |"]
    if summary:
        fv = summary.get("final_validation") or {}
        lines += [f"| stop reason | {summary.get('stop_reason')} |",
                  f"| validation loss | {fv.get('val_loss')} (initial {(summary.get('initial_validation') or {}).get('val_loss')}) |",
                  f"| tokens processed | {summary.get('tokens_processed_total'):,} |",
                  f"| train tokens/s | {summary.get('tokens_per_second_train_average')} |"]
    if eval_results:
        lines += ["", "**Held-out capability accuracy**", "", "| category | n | accuracy |", "|---|---|---|"]
        for cat, e in eval_results.get("capabilities", {}).items():
            lines.append(f"| {cat} | {e['n']} | {e['accuracy']:.3f} |" if e.get("accuracy") is not None else f"| {cat} | {e['n']} | n/a |")
    if gate:
        lines += ["", f"Promotion gate: **{'passed' if gate['passed'] else 'FAILED'}**"]
    lines += ["", "To continue: run **train-stage** with " + (
        f"`resume_artifact={bundle['artifact_name']}` (same stage, mode resume)." if not bundle["stage_complete"] else
        f"`resume_artifact={bundle['artifact_name']}` and the next stage (mode init-from).")]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------------------- CLI
def _github_output(pairs: dict[str, Any]) -> None:
    target = os.environ.get("GITHUB_OUTPUT")
    text = "".join(f"{k}={v}\n" for k, v in pairs.items())
    if target:
        with open(target, "a") as handle:
            handle.write(text)
    sys.stdout.write(text)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(prog="python -m tinymind.ci.stage_io")
    sub = p.add_subparsers(dest="cmd", required=True)
    a = sub.add_parser("runtime")
    a.add_argument("--max-hours", type=float, required=True)
    a = sub.add_parser("check-incoming")
    a.add_argument("--dir", required=True)
    a.add_argument("--stage", required=True)
    a.add_argument("--profile-config", required=True)
    a.add_argument("--mode", default="auto", choices=["auto", "resume", "init-from"])
    a.add_argument("--expect-manifest-sha256", default="")
    a.add_argument("--gate-dir", default="")
    a.add_argument("--skip-gate", action="store_true")
    a = sub.add_parser("bundle")
    a.add_argument("--run", required=True)
    a.add_argument("--dest", required=True)
    a.add_argument("--profile", required=True)
    a.add_argument("--stage", required=True)
    a.add_argument("--eval")
    a.add_argument("--probe")
    a = sub.add_parser("summary")
    a.add_argument("--bundle", required=True)
    args = p.parse_args(argv)
    try:
        if args.cmd == "runtime":
            _github_output({"seconds": runtime_seconds(args.max_hours)})
        elif args.cmd == "check-incoming":
            d = check_incoming(args.dir, stage=args.stage, profile_config=args.profile_config, requested_mode=args.mode,
                               expect_manifest_sha256=args.expect_manifest_sha256 or None, gate_dir=args.gate_dir or None,
                               skip_gate=args.skip_gate)
            _github_output({"mode": d["mode"], "checkpoint": d["checkpoint"], "parent_stage": d["bundle"]["stage"],
                            "gate": "skipped" if args.skip_gate else ("none" if not d["gate"] else ("passed" if d["gate"]["passed"] else "not-gated")),
                            "parent_step": d["bundle"]["global_step"], "parent_artifact": d["bundle"]["artifact_name"]})
        elif args.cmd == "bundle":
            extra = {}
            if args.eval:
                extra["eval_results.json"] = Path(args.eval)
            if args.probe:
                extra["runner_profile.json"] = Path(args.probe)
            m = bundle_run(args.run, args.dest, profile=args.profile, stage=args.stage, extra_files=extra)
            _github_output({"artifact_name": m["artifact_name"], "global_step": m["global_step"], "stage_complete": str(m["stage_complete"]).lower(),
                            "checkpoint_manifest_sha256": m["checkpoint_manifest_sha256"]})
        elif args.cmd == "summary":
            b = Path(args.bundle)
            m, _ = verify_bundle(b)
            summary = json.loads((b / "training_summary.json").read_text()) if (b / "training_summary.json").is_file() else None
            ev = json.loads((b / "eval_results.json").read_text()) if (b / "eval_results.json").is_file() else None
            text = summary_markdown(m, summary, eval_results=ev)
            target = os.environ.get("GITHUB_STEP_SUMMARY")
            if target:
                with open(target, "a") as handle:
                    handle.write(text)
            print(text)
    except (BundleError, ck.CheckpointError, OSError, ValueError, KeyError) as exc:
        print(f"::error::{exc}")
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
